# Generated by Django 4.0.3 on 2022-03-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kid')),
            ],
        ),
    ]
