# Generated by Django 4.0.3 on 2022-03-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='groups',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Confectionary', 'Confectionary'), ('Unknown', 'Unknown')], default='Unknown', max_length=255),
        ),
    ]
